
server:
  port: 6666
  servlet:
    context-path: /

spring:
  # rabbitmq
#  rabbitmq:
#    host: 192.168.124.2
#    port: 5674
#    username: admin
#    password: 123456
#    publisher-confirm-type: correlated
#    publisher-returns: true
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/nacos?allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true
  jpa:
    datebase: mysql
    # 显示sql
    show-sql: false
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
    redis:
      cluster:
#        nodes: 10.211.55.4:6379, 10.211.55.4:6380, 10.211.55.4:6381
      nodes: localhost:6379, localhost:6380, localhost:6381
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 20

# 日志
logging:
  # 输出级别
  level:
    root: info
  file:
    # 指定路径
    path: redis-logs
    # 最大保存天数
    # 每个文件最大大小
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 5MB
